import type { Metadata } from "next";
import "../globals.css";
import BodyWrapper from "@/components/body-wrapper";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("test");
  return (
    <BodyWrapper>
      <Header />
      <main className="antialiased">{children}</main>
    </BodyWrapper>
  );
}
