version: "3.8"

services:
  next-app:
    build:
      context: /home/ubuntu/soieu-front # 프로젝트의 절대 경로
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://43.202.20.143:8080
    restart: always
    command: "npm run start"
