// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import BodyWrapper from "@/components/body-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased  min-h-screen w-full flex justify-center items-center">
        <BodyWrapper>{children}</BodyWrapper>
      </body>
    </html>
  );
}
